- name: Installing nginx
  apt: name=nginx state=present

- name: Remote defualt nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create site config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/nginx.conf owner=root group=root mode=0644
  notify: reload nginx

