- name: Installing nginx
  apt: name=nginx state=present

- name: Remote defualt nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create site config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ ansible_facts["default_ipv4"]["address"] }}.conf owner=root group=root mode=0644
  notify: reload nginx

- name: Create simlink to config
  file: src=/etc/nginx/sites-available/{{ ansible_facts["default_ipv4"]["address"] }}.conf dest=/etc/nginx/sites-enabled/{{ ansible_facts["default_ipv4"]["address"] }}.conf state=link
  notify: reload nginx

