    - name: Clone  front app from github
      git: 
       repo: https://github.com/nbelousova/calc-front.git
       dest: /srv
    - name: Create app.js
      template: src=app.js.j2 dest=/srv/www/app.js
